apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
- ../../base
- ./ingress.yaml
images:
- name: siws/ephemeral-backend
  newName: siws/ephemeral-backend
  newTag: "14813977429"
